import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import copy from 'rollup-plugin-copy';
import scss from 'rollup-plugin-scss';
import dotenv from 'dotenv';
import manifest from './manifest.json';

dotenv.config();

const pluginName = manifest['id'];
const production = (process.env.BUILD === 'production');
const testVault = process.env.TEST_VAULT;
const pluginDir = `${testVault}/.obsidian/plugins/${pluginName}`;

const buildDir = 'build';

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
	input: 'src/main.ts',
	output: {
		dir: buildDir,
		sourcemap: 'inline',
		sourcemapExcludeSources: production,
		format: 'cjs',
		exports: 'default',
		banner,
	},
	external: ['obsidian'],
	plugins: [
		nodeResolve({
			browser: true
		}),
		commonjs(),
		typescript({
			sourceMap: !production,
			inlineSources: !production,
		}),
		scss({
			output: `${buildDir}/styles.css`,
		}),
		copy({
			targets: [
				{ src: 'manifest.json', dest: buildDir },
			],
			copyOnce: true,
		}),
		...!production ? [
			copy({
				targets: [
					{ src: `${buildDir}/*`, dest: pluginDir },
				],
			}),
		] : []
	]
};
